### ISSUE TITLE
MHW save editor sln file canno be open

### ISSUE THREAD

**Issue by Flagred** [AsteriskAmpersand/MHW-Save-Editor#11]
Edit: just find and download th exe file but when i click open it auto exit for me. Can i know there a way it  will go to the selection of the files.

Edit 2: Is there a link provided to download the application to edit the steam ID of MHW save file ( one with stable version and it working )?

**Comment by AsteriskAmpersand** [comment]
Save editor allows editing that and should work, the issue of crashing on open is separate and I'm responding on that one.
