### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by Alexaire** [AsteriskAmpersand/MHW-Save-Editor#12]
Hello a hella noob here, need help with this editor here,.....when i tried to run the .exe file it works then i tried to change the inventory it works too... Then i clicked save suddenly it crashed, something about stopped working. Turns out I can't click on backup and restore...it just crashed...halp

**Comment by Flagred** [comment]
I click open it crash after seconds wondering how you can even can open and load file to edit the file and save it

**Comment by Alexaire** [comment]
I'm using the latest version, which is the 0.4.0.0 version, didn't work then i switched again to the 0.3.3 version too and the result stayed the same :/

**Comment by AsteriskAmpersand** [comment]
Are you trying to save while the game is open, or while the save is open in another program?

**Comment by Flagred** [comment]
Nope I don't even manage to open. Hope you can get your program function
well although I find a way to edit steam ID using hex already. Thank for
your reply

**Comment by Alexaire** [comment]
I try to save while the game is open, and it crashed not the game.....just the program, i dunno why...i put 400+ hours in the ps4 version i just wanted to skip the grind

**Comment by Flagred** [comment]
Do you need open game order to edit. That sound no logic right ? As click
load will direct  crash in your save editor. Do let know how you make your
save editor working instead of only click load and choose file.

**Comment by Alexaire** [comment]
Well... I run the game with the editor on tried to save the edited version result = crash
I close the game, open save data location tried to edit the inventory...works well then i click save result = crash

**Comment by AsteriskAmpersand** [comment]
Game shouldn't be open when you are editing. Have the game closed when using the editor.

Additionally are you using the latest release? Furthermore, is your copy of the game legit or a pirated version?

**Comment by Alexaire** [comment]
Mine's the legit version, and i'm using the latest release version

**Comment by Flagred** [comment]
I close game edit = fail but never mind I got hex editor to edit. The
problem is it crash when I click load ( I download latest version ) . It no
about legit or pirate. Cause the save file don't have legit and pirate (
correct me if I wrong ) unless your engine can get information of steam ID
in save file (in this case I don't think your save engine got ). Most
people using legit mhw and got crash using your editor too.It just your
program won't work properly. Anyway thanks for reply.

**Comment by AsteriskAmpersand** [comment]
Alexaire problem is solved now and I can't even figure out what Flagred is complaining about. I'm closing the issue as solved and unrelated to the editor.
