### ISSUE TITLE
How to edit winter star ticket ? Cant edit ?

### ISSUE THREAD

**Issue by Flagred** [AsteriskAmpersand/MHW-Save-Editor#15]
The editor work for me and it just anti virus issue i think. Can your editor edit the hidden item like winter star ticket ? Thank

**Comment by AsteriskAmpersand** [comment]
They aren't hidden items. It can as long as the item list is updated to the latest patch. This happens whenever I get around doing this. Releases version will indicate if it's been updated to latest patch.
