### ISSUE TITLE
Investigation how to use

### ISSUE THREAD

**Issue by Flagred** [AsteriskAmpersand/MHW-Save-Editor#16]
how to use investigation got any thing like  a notes to explain ? i put nergi at slot one and at elder place but no boss appear wtf

**Comment by AsteriskAmpersand** [comment]
This is not the place for usage tutorials. This is clearly marked a research tool and not a final version, if you don't know how to use it wait for the official final release.

**Comment by Flagred** [comment]
Excuse to ask I edit investigation but the nergigante no available. Do fix
investigation and also help allow more than one elder dragon on
investigation.
