### ISSUE TITLE
Update item list

### ISSUE THREAD

**Issue by Zottelchen** [AsteriskAmpersand/MHW-Save-Editor#19]
New patch came out and behemoth items don't seem to be shown yet. Please update.

**Comment by AsteriskAmpersand** [comment]
They are there, just missing gmd entries. If you have one of them alreayd you can identify them easily and if you don't don't just give them to yourself because you break flags doing that. It will be updated when it's updated, strings are not any sort of priority.

**Comment by AsteriskAmpersand** [comment]
Issue is closed as of latest release.
