### ISSUE TITLE
Hunter XP not being correctly modified

### ISSUE THREAD

**Issue by ravingraybits34** [AsteriskAmpersand/MHW-Save-Editor#22]
Changing the Hunter Rank and Hunter XP values to match those of the Hunter Rank seems to bug Hunter Rank entirely. The bar no longer increases when completing quests.

**Comment by AsteriskAmpersand** [comment]
Not a bug. Hunter rank will not increase as long as hunter xp is levels behind, this is a game mechanic, simply raise hunter xp and the game autoupdates the hunter rank.
