### ISSUE TITLE
Money and research points not registered within the game

### ISSUE THREAD

**Issue by Grapesfruit** [AsteriskAmpersand/MHW-Save-Editor#23]
While editing the amount of money and research points, program outlines the number with red, and it is later not registered within the game. I tried different thousands and decimals separators ( , and . )
Thank you in advance!

**Comment by PlacementProduit** [comment]
Same issue for the hunter experience.
I thanks you in advance too!

**Comment by AfxousaAjagara** [comment]
I just fix this issue. Don't know reason, but I have multiple profile for MHW save. So if you search for right profile and save, you have no problem.

**Comment by Sebastian1989101** [comment]
I have the issue too and it looks like the binding on the textbox is not working properly because it gets a red border if I enter a value

**Comment by AsteriskAmpersand** [comment]
Set locale to english, problem is wpf doesn't deal with locale properly.

**Comment by Sebastian1989101** [comment]
@AsteriskAmpersand actually I solved it myself by removing the "N0" number formatting on the TextBox and compile it myself. Another solution would be to set the UI Thread Culture to Invariant if your application depends on english so much. And I guess what could work too is a StringFormat Binding instead of the TextFormat property on the TextBox but it is quite some time since I developed WPF so I'm not 100% sure about the last option.

**Comment by An70ni092** [comment]
Help, i also have this problem and i don't solve even if i set the game in English

**Comment by only1dragonr** [comment]
how u guys removed number formating on the text box and compiled? can someone help me please? pc is not my domain... xd just to save time .... alsow i am very gratefull for this save editor very well done... i just idk how to solve red numbers problem... can someone explayin to me in simple and easy steps as well?

**Comment by Sebastian1989101** [comment]
@only1dragonr You should not do this if you don't know what you do. I mentioned the possible solutions above so if the owner of this repo does not want to fix it and if you don't understand how to fix it yourself you are pretty much out of luck. Before you can actual fix it and compile this project you need to setup the whole development environment so in this case Visual Studio with WPF/Desktop development.

**Comment by DragonHunterMilenium** [comment]
okey thx for reply i understood... is not simple at all :)
