### ISSUE TITLE
Closed when saves the data

### ISSUE THREAD

**Issue by Lycan094** [AsteriskAmpersand/MHW-Save-Editor#25]
Hello, I have a problem, when I save the data the program close, I tried to deactivate Windows  defender but the problem continues (I opened the SAVEDATA1000).
Thx

**Comment by AsteriskAmpersand** [comment]
Are the changes saved though?

**Comment by Lycan094** [comment]
no, changes are not saved

**Comment by AsteriskAmpersand** [comment]
Have you tried running it in admin mode to see if it also happens in that case?

**Comment by Lycan094** [comment]
Yes, but its the same case, the app clase and changes are not save

**Comment by shouborno** [comment]
Exactly same case here.
