### ISSUE TITLE
HR got locked after changing, from 250 to 320

### ISSUE THREAD

**Issue by Crowoly** [AsteriskAmpersand/MHW-Save-Editor#27]
it looks like Hunter rank can still be changed on editor but Hunter XP is definitely locked. how can I solve this?

**Comment by slarm001** [comment]
I can second this. I changed my HR but now the XP is locked...

**Comment by Graydenn** [comment]
Did you change the XP as well? Sometimes if you just change the HR then the amount of progress from for example 250 to 320 is so small that it doesn't look like anything changed.

**Comment by AsteriskAmpersand** [comment]
Changing HR means your XP is behind so until it catches up it looks like your level is locked. Edit Hunter XP not HR directly.
