### ISSUE TITLE
Just a Suggestion or request.

### ISSUE THREAD

**Issue by skyreig7622** [AsteriskAmpersand/MHW-Save-Editor#29]
Sorry to post it here, can't seems to find the suggestion tab or message tab, so i'm just gonna put it here. 
if possible, would like to request for a guildcard editor, which can edit data like Weapon Usage, Monster Size, or reset specific Arena time.
Thank in Advance.

**Comment by AsteriskAmpersand** [comment]
Guild cards just show the underlying save data, they are recalculated constantly. The other save data could be added but requires mapping it's location first. The project is most likely being migrated to another less atrocious language and framework before I do more work on it however.
