### ISSUE TITLE
Game not using edited save?

### ISSUE THREAD

**Issue by CommanderPhoenix** [AsteriskAmpersand/MHW-Save-Editor#36]
I tried to make some Investigations so I wouldn't be farming forever for Small and Big crowns, and give myself a bunch of easily farmed items to save some time, and I made sure to save the changes, but when I open the game, neither the new investigations or the items are in my game. When I go back to check, though, the save editor shows that I still have the items and Investigations in there. How would I fix this?

**Comment by AsteriskAmpersand** [comment]
User error.
