### ISSUE TITLE
The app stopped working

### ISSUE THREAD

**Issue by Johnny-Ridden-R2** [AsteriskAmpersand/MHW-Save-Editor#40]
The app was running until 3 days ago, but it has stopped working since yesterday

Click on the exe file to launch the app
I'm trying to open a file, but the app stops

why?

**Comment by AsteriskAmpersand** [comment]
Cannot repro. And nothing was changed in the last few days so it's on you.

**Comment by hatsujc** [comment]
I can confirm that the app crashed when I clicked File menu. The recent Windows update (KB4515384, KB4514359, KB4515383) are probably the culprits. I could use the save editor just fine before the automatic update.
