### ISSUE TITLE
Editing a numerical field on information tab goes red on values over 999

### ISSUE THREAD

**Issue by seth-rah** [AsteriskAmpersand/MHW-Save-Editor#45]
## Summary

When changing the value in the Zenny, Research Points or Hunter XP field, an auto format gets applied to the field that expects a numerical value. As soon as a value larger than 999 is entered into the field it gets a red border. This value can be lower, or even an undo to the previous entry. 

My theory is that the formatting applying a space between certain values causes this to occur, it's being parsed with the space on edited, and being seen as a non numerical.

I checked issue #23 for solutions first, however dev responses there don't apply to this situation, as all my locales are already set to English.

The last comment on #23 was accurate, I removed the numerical formatting on the field and it managed to save the data fine.  

![image](https://user-images.githubusercontent.com/2222634/68082028-0b175d80-fe20-11e9-9c4f-7a10c163eccd.png) 
![image](https://user-images.githubusercontent.com/2222634/68082049-59c4f780-fe20-11e9-8394-1b09646b3d80.png)

**Comment by Verplempert** [comment]
How do i remove the numerical formatting on the fields, so i can enter values larger than 999?
Could you elaborate? Thx in advance.

**Comment by seth-rah** [comment]
You will need to have visual studio downloaded, and then remove the "N0" number formatting on the TextBox, and then compile.

**Comment by AsteriskAmpersand** [comment]
Project is deprecated, being ported to python. Will keep this in mind in the next iteration however.

**Comment by morsley** [comment]
@AsteriskAmpersand Do you have a new repo for the python port yet?  Would love to check it out / contribute.
