### ISSUE TITLE
Cant edit own savefile?

### ISSUE THREAD

**Issue by ThePRTKILLER** [AsteriskAmpersand/MHW-Save-Editor#49]
I can edit savefiles from others that i download from the internet but my own i cant edit.
When i try to it always look like this
![Unbenannt](https://user-images.githubusercontent.com/59847295/72289966-82e9db80-364c-11ea-9a9f-263822aa50a5.PNG)

**Comment by ObsidianGrimoire** [comment]
Most recent patch changed the encryption scheme used by the game. Just have to wait for the tool to update.

**Comment by AsteriskAmpersand** [comment]
Not Iceborne compatible.
