### ISSUE TITLE
MHW-Save-Editor not loading Save Data

### ISSUE THREAD

**Issue by Bapabooey** [AsteriskAmpersand/MHW-Save-Editor#50]
So I've been using this perfectly fine, but recently after getting the Iceborne update this has been happening, I go to the path I've always used to get to my save data: C:\Program Files (x86)\Steam\userdata\487913135\582010\remote 

And it just doesn't load anything, Hunter name, a bunch of symbols, Palico name, a bunch of symbols, Z, blank, Resources, blank, all investigations gone, all items in both inventory and boxes, gone. 

Even when I use the backed up data I made for my save, still nothing.

Any idea how to fix this?

**Comment by Bapabooey** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/53815572/73138009-9a00d400-4023-11ea-9721-420017cb3e8b.png)
![Screenshot (10)](https://user-images.githubusercontent.com/53815572/73138014-9f5e1e80-4023-11ea-9076-118926236a61.png)
![Screenshot (11)](https://user-images.githubusercontent.com/53815572/73138018-a422d280-4023-11ea-887f-ca9bb50386b1.png)
![Screenshot (12)](https://user-images.githubusercontent.com/53815572/73138029-b3a21b80-4023-11ea-83c9-a9f7cedf23c6.png)
![Screenshot (13)](https://user-images.githubusercontent.com/53815572/73138031-bef54700-4023-11ea-8cef-66bedb86cd03.png)

**Comment by TheEvoluder** [comment]
Iceborne added an extra (and extremely pointless) layer of encryption for the save files, which the editor cant read yet

**Comment by TheEvoluder** [comment]
you'll have to wait until Asterik updates the editor
