### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by fahrenhheit** [AsteriskAmpersand/MHW-Save-Editor#51]
Sorry, have no idea how. Downloaded it with the green clone button but there is no exe file so i can open my savedata1000 with. Help me please.

**Comment by Vikijaka** [comment]
Take in Mind that you are not able to use this Editor, if you have updated in the last few Month.

With the Iceborne Update encryption got changed/added

https://github.com/AsteriskAmpersand/MHW-Save-Editor/releases

**Comment by fahrenhheit** [comment]
i use the 166925 crack version. is that ok with the editor?

**Comment by Vikijaka** [comment]
Sorry i don't talk about/support piracy (in public)
17 ~ 20€ official reseller -> https://isthereanydeal.com/game/monsterhunterworld/info/
unofficial -> with a VPN from Russia/Brazilia its even cheaper
